/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package student_pro;

/**
 *
 * @author SODA
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_addstudent = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btn_operation = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btn_showstudent = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btn_addadmin = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btn_adminoperation = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btn_showadmin = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        home = new javax.swing.JMenuItem();
        logout = new javax.swing.JMenuItem();
        menu_about = new javax.swing.JMenu();
        about = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(796, 658));
        setMinimumSize(new java.awt.Dimension(796, 658));
        setResizable(false);
        getContentPane().setLayout(null);

        btn_addstudent.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\OneDrive\\Documents\\NetBeansProjects\\Student_pro\\src\\image\\AddStudent.png")); // NOI18N
        btn_addstudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addstudentActionPerformed(evt);
            }
        });
        getContentPane().add(btn_addstudent);
        btn_addstudent.setBounds(60, 170, 150, 160);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Add Student");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(80, 340, 120, 21);

        btn_operation.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\OneDrive\\Documents\\NetBeansProjects\\Student_pro\\src\\image\\configuration.png")); // NOI18N
        btn_operation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_operationActionPerformed(evt);
            }
        });
        getContentPane().add(btn_operation);
        btn_operation.setBounds(320, 170, 160, 160);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Operation");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(360, 340, 120, 21);

        btn_showstudent.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\OneDrive\\Documents\\NetBeansProjects\\Student_pro\\src\\image\\showStudent.png")); // NOI18N
        btn_showstudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_showstudentActionPerformed(evt);
            }
        });
        getContentPane().add(btn_showstudent);
        btn_showstudent.setBounds(560, 170, 170, 160);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Show Student");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(600, 340, 120, 21);

        btn_addadmin.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\OneDrive\\Documents\\NetBeansProjects\\Student_pro\\src\\image\\addAdmin.png")); // NOI18N
        btn_addadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addadminActionPerformed(evt);
            }
        });
        getContentPane().add(btn_addadmin);
        btn_addadmin.setBounds(60, 390, 150, 160);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Add Admin");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 560, 120, 21);

        btn_adminoperation.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\OneDrive\\Documents\\NetBeansProjects\\Student_pro\\src\\image\\configuration1.png")); // NOI18N
        btn_adminoperation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_adminoperationActionPerformed(evt);
            }
        });
        getContentPane().add(btn_adminoperation);
        btn_adminoperation.setBounds(320, 390, 160, 160);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Operation");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(360, 560, 120, 21);

        btn_showadmin.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\OneDrive\\Documents\\NetBeansProjects\\Student_pro\\src\\image\\showAdmin.png")); // NOI18N
        btn_showadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_showadminActionPerformed(evt);
            }
        });
        getContentPane().add(btn_showadmin);
        btn_showadmin.setBounds(560, 390, 170, 160);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Show Admin");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(600, 560, 120, 21);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Home", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\OneDrive\\Documents\\NetBeansProjects\\Student_pro\\src\\image\\logo.png")); // NOI18N
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 800, 640);

        jMenu1.setText("File");

        home.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        home.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\OneDrive\\Documents\\NetBeansProjects\\Student_pro\\src\\image\\home.png")); // NOI18N
        home.setText("Home");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        jMenu1.add(home);

        logout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        logout.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\OneDrive\\Documents\\NetBeansProjects\\Student_pro\\src\\image\\logout.png")); // NOI18N
        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jMenu1.add(logout);

        jMenuBar1.add(jMenu1);

        menu_about.setText("About");

        about.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        about.setText("About");
        about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutActionPerformed(evt);
            }
        });
        menu_about.add(about);

        jMenuBar1.add(menu_about);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(810, 695));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addstudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addstudentActionPerformed
        dispose();
        Addstudent addstudent = new Addstudent();
        addstudent.show();
    }//GEN-LAST:event_btn_addstudentActionPerformed

    private void btn_operationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_operationActionPerformed
        dispose();
        Student_update operation = new Student_update();
        operation.show();
    }//GEN-LAST:event_btn_operationActionPerformed

    private void btn_showstudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_showstudentActionPerformed
        dispose();
       ShowStudent show_stu = new ShowStudent();
        show_stu.show();
    }//GEN-LAST:event_btn_showstudentActionPerformed

    private void btn_addadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addadminActionPerformed
       dispose();
       Add_Amin admin = new Add_Amin();
       admin.show();
    }//GEN-LAST:event_btn_addadminActionPerformed

    private void btn_adminoperationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_adminoperationActionPerformed
        dispose();
        Admin_Update admin = new Admin_Update();
        admin.show();
    }//GEN-LAST:event_btn_adminoperationActionPerformed

    private void btn_showadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_showadminActionPerformed
        dispose();
        Show_Admin show_admin = new Show_Admin();
        show_admin.show();
    }//GEN-LAST:event_btn_showadminActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        dispose();
        Home home = new Home();
        home.show();
    }//GEN-LAST:event_homeActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        dispose();
        Login login = new Login();
        login.show();
    }//GEN-LAST:event_logoutActionPerformed

    private void aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutActionPerformed
        dispose();
        About about= new About();
        about.show();
    }//GEN-LAST:event_aboutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem about;
    private javax.swing.JButton btn_addadmin;
    private javax.swing.JButton btn_addstudent;
    private javax.swing.JButton btn_adminoperation;
    private javax.swing.JButton btn_operation;
    private javax.swing.JButton btn_showadmin;
    private javax.swing.JButton btn_showstudent;
    private javax.swing.JMenuItem home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem logout;
    private javax.swing.JMenu menu_about;
    // End of variables declaration//GEN-END:variables
}
